# Generated by Django 5.2.6 on 2026-04-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
